name: CI Test HLA-PepClust on Ubuntu, macOS, and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create virtual environment and install dependencies
        shell: bash
        run: |
          python -m venv hlapepclust-env
          if [ "$RUNNER_OS" == "Windows" ]; then
            source hlapepclust-env/Scripts/activate
          else
            source hlapepclust-env/bin/activate
          fi
          pip install --upgrade pip
          pip install -e .
          
      - name: Run `clust-search` --help command
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            source hlapepclust-env/Scripts/activate
          else
            source hlapepclust-env/bin/activate
          fi
          clust-search -h

      - name: Run `clust-search` --version command
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            source hlapepclust-env/Scripts/activate
          else
            source hlapepclust-env/bin/activate
          fi
          clust-search --version
      
      - name: Check current directory
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            source hlapepclust-env/Scripts/activate
          else
            source hlapepclust-env/bin/activate
          fi
          ls
          pwd

      - name: Run `clust-search` command with test data
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            source hlapepclust-env/Scripts/activate
          else
            source hlapepclust-env/bin/activate
          fi
          clust-search data/D90_HLA_3844874 data/ref_data/Gibbs_motifs_human/output_matrices_human --hla_types A0201,A0101,B1302,B3503,C0401 --n_clusters 6 --output test_results --processes 4