name: CI: Test HLA-PepClust on Ubuntu, macOS, and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create virtual environment and install dependencies
        shell: bash
        run: |
          python -m venv hlapepclust-env
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "source hlapepclust-env/Scripts/activate" >> $GITHUB_ENV
          else
            echo "source hlapepclust-env/bin/activate" >> $GITHUB_ENV
          fi
          source $GITHUB_ENV
          pip install --upgrade pip
          pip install .

  test:
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Activate virtual environment and install dependencies
        shell: bash
        run: |
          source $GITHUB_ENV
          pip install --upgrade pip
          pip install .

      - name: Download test data (example)
        shell: bash
        run: |
          mkdir -p data
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            Invoke-WebRequest -Uri "https://github.com/Sanpme66/HLA-PepClust/raw/new-features/data.zip" -OutFile "data.zip"
          else
            wget -O data.zip "https://github.com/Sanpme66/HLA-PepClust/raw/new-features/data.zip"
          fi
          unzip data.zip -d data/

      - name: Run `clust-search` --help command
        shell: bash
        run: |
          source $GITHUB_ENV
          clust-search -h

      - name: Run `clust-search` --version command
        shell: bash
        run: |
          source $GITHUB_ENV
          clust-search --version
      
      - name: Check current directory
        run: |
          ls
          pwd

      - name: Run `clust-search` command with test data
        shell: bash
        run: |
          source $GITHUB_ENV
          clust-search data/D90_HLA_3844874 data/ref_data/Gibbs_motifs_human/output_matrices_human --hla_types A0201,A0101,B1302,B3503,C0401 --n_clusters 6 --output test_results --processes 4

      - name: Deactivate virtual environment
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            exit 0
          else
            deactivate
          fi
