name: CI Test HLA-PepClust on Ubuntu, macOS, and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          # Verify installation was successful
          pip list
          
      - name: Run `clust-search` --help command
        shell: bash
        run: clust-search -h

      - name: Run `clust-search` --version command
        shell: bash
        run: clust-search --version
      
      - name: Check current directory
        shell: bash
        run: |
          ls -la
          pwd

      - name: Run `clust-search` command with test data
        shell: bash
        run: |
          # Verify data directories exist
          if [ ! -d "data/D90_HLA_3844874" ] || [ ! -d "data/ref_data/Gibbs_motifs_human/output_matrices_human" ]; then
            echo "Warning: Data directories not found, listing available data:"
            find data -type d | sort
          fi
          
          # Run with reduced processes to avoid memory issues
          clust-search data/D90_HLA_3844874 data/ref_data/Gibbs_motifs_human/output_matrices_human --hla_types A0201,A0101,B1302,B3503,C0401 --n_clusters 6 --output test_results --processes 2