name: CI Test HLA-PepClust on Ubuntu, macOS, and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          # Verify installation was successful
          pip list

      # Special handling for Windows to deal with encoding issues
      - name: Set up UTF-8 environment for Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          echo "Setting PYTHONIOENCODING=utf-8"
          echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
          
      - name: Run `clust-search` --help command
        if: runner.os != 'Windows'
        shell: bash
        run: clust-search -h || echo "Help command failed, but continuing..."
        
      - name: Run `clust-search` --help command (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          chcp 65001
          clust-search -h > help_output.txt || echo Help command failed, but continuing...
          type help_output.txt
        
      - name: Run `clust-search` --version command
        if: runner.os != 'Windows'
        shell: bash
        run: clust-search --version || echo "Version command failed, but continuing..."
        
      - name: Run `clust-search` --version command (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          chcp 65001
          clust-search --version > version_output.txt || echo Version command failed, but continuing...
          type version_output.txt
      
      - name: Check data directories
        shell: bash
        run: |
          echo "Current directory contents:"
          ls -la
          
          echo "Data directory contents:"
          if [ -d "data" ]; then
            ls -la data
            echo "Subdirectories in data:"
            find data -type d -maxdepth 2 || dir /s /b data
          else
            echo "ERROR: 'data' directory not found!"
            exit 1
          fi
          
          if [ ! -d "data/D90_HLA_3844874" ]; then
            echo "ERROR: Input data directory 'data/D90_HLA_3844874' not found!"
            exit 1
          fi
          
          if [ ! -d "data/ref_data" ]; then
            echo "ERROR: Reference data directory 'data/ref_data' not found!"
            exit 1
          fi

      - name: Run `clust-search` command with test data without HLA allele [Human]
        if: runner.os != 'Windows'
        shell: bash
        run: |
          # Create output directory
          mkdir -p test_results
          
          # Run with species parameter
          clust-search data/D90_HLA_3844874 data/ref_data/ \
            --n_clusters 6 \
            --output test_results \
            --processes 2 \
            --species human

      - name: Run `clust-search` command with test data without HLA allele [Human] (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          chcp 65001
          mkdir test_results 2>nul
          clust-search data/D90_HLA_3844874 data/ref_data/ --n_clusters 6 --output test_results --processes 2 --species human
      
      - name: Run `clust-search` command with test data and HLA allele types [Human]
        if: runner.os != 'Windows'
        shell: bash
        run: |
          # Create output directory
          mkdir -p test_results
          
          # Run with HLA allele types parameter
          clust-search data/D90_HLA_3844874 data/ref_data/ \
            --hla_types A0201,A0101,B1302,B3503,C0401 \
            --n_clusters 6 \
            --output test_results \
            --processes 2 \
            --species human

      - name: Run `clust-search` command with test data and HLA allele types [Human] (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          chcp 65001
          mkdir test_results 2>nul
          clust-search data/D90_HLA_3844874 data/ref_data/ --hla_types A0201,A0101,B1302,B3503,C0401 --n_clusters 6 --output test_results --processes 2 --species human
        
      - name: Run `clust-search` command with test data and HLA allele types [Mouse]
        if: runner.os != 'Windows'
        shell: bash
        run: |
          # Create output directory
          mkdir -p test_results
          
          # Run with HLA allele types parameter
          clust-search data/9mersonly data/ref_data/ \
            --hla_types H2_Kb,H2_Db,H2_Dd,H2_Dd,H2_Ld \
            --n_clusters 5 \
            --output test_results \
            --processes 2 \
            --species mouse

      - name: Run `clust-search` command with test data and HLA allele types [Mouse] (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          chcp 65001
          mkdir test_results 2>nul
          clust-search data/9mersonly data/ref_data/ --hla_types H2_Kb,H2_Db,H2_Dd,H2_Dd,H2_Ld --n_clusters 5 --output test_results --processes 2 --species mouse

      - name: Verify test results
        shell: bash
        run: |
          echo "Checking test results directory:"
          if [ -d "test_results" ]; then
            ls -la test_results
            echo "Success! Test results generated."
          else
            echo "ERROR: No test results directory found!"
            exit 1
          fi