name: HLA-PepClust Python Package CI

on:
  push:
    branches: [ "new-features" ]
  pull_request:
    branches: [ "new-features" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install Dependencies
      run: |
        poetry install --no-interaction --no-root
        poetry run pip install flake8 

    - name: Lint with flake8
      run: |
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests with pytest
      run: |
        poetry run pytest

    - name: Verify CLI Help Command
      run: |
        poetry run cluster-search -h
