name: Test HLA-PepClust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create and activate virtual environment
        run: |
          python3 -m venv hlapepclust-env
          source hlapepclust-env/bin/activate
          pip install --upgrade pip
          pip install .

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Activate virtual environment and install dependencies
        run: |
          python3 -m venv hlapepclust-env
          source hlapepclust-env/bin/activate
          pip install --upgrade pip
          pip install .

      - name: Download test data (example)
        run: |
          mkdir -p data
          wget -O data.zip https://github.com/Sanpme66/HLA-PepClust/raw/new-features/data.zip
          unzip data.zip -d data/

      - name: Run `clust-search` --help command
        run: |
          clust-search -h
          
      - name: Run `clust-search` --version command
        run: |
          clust-search --version

      - name: Run `clust-search` command
        run: |
          source hlapepclust-env/bin/activate
          clust-search data/D90_HLA_3844874 data/ref_data/Gibbs_motifs_human/output_matrices_human --hla_types A0201,A0101,B1302,B3503,C0401 --n_clusters 6 --output test_results --processes 4

      - name: Deactivate virtual environment
        run: deactivate
